export const REGISTER_PRODUCT = "REGISTER_PRODUCT"
export const REGISTER_PRODUCT_SUCESS = "REGISTER_PRODUCT_SUCESS"
export const REGISTER_PRODUCT_ERROR = "REGISTER_PRODUCT_ERROR"

export const LIST_PRODUCTS = "LIST_PRODUCTS"
export const REQUEST_PRODUCTS = "REQUEST_PRODUCTS"