// login user
export const LOGIN_USER_REQUEST = "LOGIN_USER_REQUEST"
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS"
export const LOGIN_USER_ERROR = "LOGIN_USER_ERROR"
export const LOGOUT_USER = "LOGOUT_USER"

//register user

export const REGISTER_USER = "REGISTER_USER"
export const REGISTER_USER_SUCESS = "REGISTER_USER_SUCESS"
export const REGISTER_USER_ERROR = "REGISTER_USER_ERROR"

//get user

export const LIST_USERS = "LIST_USERS"
export const LIST_USERS_SUCESS = "LIST_USERS_SUCESS"
export const LIST_USERS_ERROR = "LIST_USERS_ERROR"